### ISSUE TITLE
allow-methods

### ISSUE THREAD

**Issue by angelasoler** [angelasoler/WebServ#90]
uma rota só podera executar os metodos permitidos, caso tiver está configuração

**Comment by eusourenan** [comment]
Se o usuário mandar um método inválido é possível identificar em `Request::getMethodAction`. 

- Uma vez que eu identifiquei, posso simplesmente retornar a página com erro? 

- Ou, para manter o design de projeto, é melhor o fluxo continuar e eu fazer a classe GET retornar a página de "Method Not Allowed"?
